In [26]:
import tensorflow as tf

In [1]:
from tensorflow.keras.models import load_model

2024-09-17 22:30:24.357257: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-17 22:30:24.366765: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-17 22:30:24.394653: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-17 22:30:24.438988: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-17 22:30:24.451319: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-17 22:30:24.482568: I tensorflow/core/platform/cpu_feature_gu

In [2]:
model=load_model('model.h5')

In [3]:
import pandas as pd
import numpy as np

In [12]:
df=pd.read_csv('test.csv')

In [13]:
def hex_to_bytes(hex_string, max_len=256):
    byte_seq = bytes.fromhex(hex_string)
    byte_seq = byte_seq.ljust(max_len, b'\x00')[:max_len]
    return byte_seq


In [14]:
max_len = 256
byte_sequences = np.array([np.frombuffer(hex_to_bytes(seq, max_len), dtype=np.uint8).reshape(16, 16, 1)
                           for seq in df['byte_sequence']])

In [15]:
byte_sequences.shape

(9, 16, 16, 1)

In [25]:
predictions=model.predict(byte_sequences)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


In [35]:
predictions*100

array([[1.7624486e-02, 1.6514025e+01, 8.3468346e+01],
       [1.7125262e+00, 2.5386978e+01, 7.2900490e+01],
       [1.3275418e-02, 2.5725809e+01, 7.4260918e+01],
       [9.4349924e-03, 3.2700260e+01, 6.7290291e+01],
       [1.1184556e-02, 2.7439445e+01, 7.2549370e+01],
       [1.6977072e-02, 2.3260176e+01, 7.6722839e+01],
       [1.0825873e-02, 2.8148430e+01, 7.1840744e+01],
       [8.6864326e-03, 2.9317417e+01, 7.0673904e+01],
       [2.7668353e-02, 4.8623669e+01, 5.1348663e+01]], dtype=float32)

In [31]:
predicted_class_indices = tf.argmax(predictions, axis=1)
predicted_class_names = [class_names[i] for i in predicted_class_indices]

print(predicted_class_names,predicted_class_indices)


['DES', 'DES', 'DES', 'DES', 'DES', 'DES', 'DES', 'DES', 'DES'] tf.Tensor([2 2 2 2 2 2 2 2 2], shape=(9,), dtype=int64)


In [7]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

In [8]:
label_encoder = LabelEncoder()
algorithms = label_encoder.fit_transform(df['algorithm'])
y = to_categorical(algorithms)

In [37]:
label_encoder.classes_

array(['AES-256', 'Blowfish', 'DES'], dtype=object)

In [9]:
byte_sequences.shape

(1000, 16, 16, 1)

In [17]:
y

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [10]:
y.shape

(1000, 3)

In [11]:
loss, accuracy = model.evaluate(byte_sequences, y, verbose=1)

32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6916 - loss: 0.4635


In [37]:
# Build the model by calling it on some input
model.predict(np.zeros((1, 16,16)))  # Replace `input_shape` with the actual shape

# Now evaluate the model



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[1.1343460e-07, 4.9605823e-01, 5.0394166e-01]], dtype=float32)

In [38]:
loss, accuracy = model.evaluate(byte_sequences, y, verbose=1)

AttributeError: 'NoneType' object has no attribute 'items'

In [39]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


In [29]:
model1=load_model("rnnmodel.h5")

In [30]:
model1.predict(byte_sequences)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 528ms/step


array([[0.0000000e+00, 9.9999994e-01, 1.5011047e-13],
       [0.0000000e+00, 9.9999994e-01, 6.1787228e-11],
       [0.0000000e+00, 9.9999994e-01, 1.3964062e-12],
       [0.0000000e+00, 9.9999958e-01, 3.4184228e-07],
       [0.0000000e+00, 9.9999994e-01, 8.0793130e-13],
       [0.0000000e+00, 9.9999994e-01, 1.2674133e-12],
       [0.0000000e+00, 9.9999994e-01, 3.1603026e-10],
       [0.0000000e+00, 9.9999994e-01, 4.3096425e-12],
       [1.8715151e-07, 4.9310070e-01, 5.0689906e-01]], dtype=float32)

In [36]:
predicted_class_indices = tf.argmax(predictions, axis=1)
predicted_class_names = [class_names[i] for i in predicted_class_indices]

print(predicted_class_names)

['DES', 'DES', 'DES', 'DES', 'DES', 'DES', 'DES', 'DES', 'DES']
