In [ ]:
from tensorflow.keras.models import load_model

2024-09-29 18:18:29.836879: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-29 18:18:29.972456: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-29 18:18:30.134994: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-29 18:18:30.278371: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-29 18:18:30.316262: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-29 18:18:30.531547: I tensorflow/core/platform/cpu_feature_gu

In [ ]:
model1=load_model('modelcnn.h5')
model2=load_model('rnnmodel.h5')
model3=load_model('modelASYMMETRICCNN.h5')
model4=load_model('modelasymmetricrnn.h5')
model5=load_model('modelstreamcnn.h5')
model6=load_model('modelstreamrnn.h5')
models=[model1,model2,model3,model4,model5,model6]

In [ ]:
import pandas as pd

In [ ]:
dataset=pd.read_csv('/media/narayanan/New Volume/sih/test.csv')

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 1 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   byte_sequence  9 non-null      object
dtypes: object(1)
memory usage: 204.0+ bytes


In [ ]:
import numpy as np

In [ ]:
def hex_to_bytes(hex_string, max_len=256):
    byte_seq = bytes.fromhex(hex_string)
    byte_seq = byte_seq.ljust(max_len, b'\x00')[:max_len]
    return byte_seq


In [ ]:
max_len = 256
byte_sequences = np.array([np.frombuffer(hex_to_bytes(seq, max_len), dtype=np.uint8).reshape(16, 16, 1)
                           for seq in dataset['byte_sequence']])

In [ ]:
se1 = np.array([np.frombuffer(hex_to_bytes(dataset['byte_sequence'][0], max_len), dtype=np.uint8).reshape(16, 16, 1)])

In [ ]:
print(se1)

[[[[164]
   [ 35]
   [105]
   [159]
   [132]
   [169]
   [104]
   [194]
   [ 68]
   [ 37]
   [152]
   [240]
   [106]
   [199]
   [ 68]
   [133]]

  [[218]
   [214]
   [217]
   [  8]
   [247]
   [123]
   [239]
   [182]
   [120]
   [175]
   [178]
   [155]
   [149]
   [ 92]
   [  4]
   [212]]

  [[144]
   [238]
   [153]
   [250]
   [ 42]
   [154]
   [ 43]
   [173]
   [153]
   [159]
   [156]
   [ 60]
   [201]
   [ 46]
   [  6]
   [ 81]]

  [[249]
   [240]
   [133]
   [128]
   [233]
   [149]
   [138]
   [126]
   [170]
   [250]
   [194]
   [194]
   [145]
   [ 96]
   [183]
   [ 95]]

  [[190]
   [ 71]
   [123]
   [108]
   [247]
   [107]
   [253]
   [164]
   [211]
   [105]
   [223]
   [ 53]
   [ 93]
   [101]
   [255]
   [249]]

  [[120]
   [ 15]
   [ 82]
   [187]
   [114]
   [ 21]
   [ 68]
   [115]
   [177]
   [197]
   [190]
   [ 95]
   [178]
   [165]
   [242]
   [ 26]]

  [[111]
   [ 46]
   [213]
   [ 51]
   [ 64]
   [200]
   [ 99]
   [ 86]
   [166]
   [115]
   [ 89]
   [196]
   [ 67]
   [242

In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

def predict_symmetric(arr):
    label1 = ['AES-256', 'Blowfish', 'DES']
    label2=['DSA', 'ECC', 'RSA-2048', 'RSA-4096']
    label3=['ChaCha20', 'RC4', 'Salsa20']
    encoder1 = LabelEncoder()
    encoder1.fit(label1)
    encoder2 = LabelEncoder()
    encoder2.fit(label2)
    encoder3 = LabelEncoder()
    encoder3.fit(label3)
    predicted_probabilities1 = model1.predict(arr)
    predicted_probabilities2 = model2.predict(arr)
    predicted_probabilities3 = model3.predict(arr)
    predicted_probabilities4 = model4.predict(arr)
    predicted_probabilities5 = model5.predict(arr)
    predicted_probabilities6 = model6.predict(arr)


    predicted_labels_with_probabilities1 = {label: prob for label, prob in zip(encoder1.classes_, predicted_probabilities1[0])}
    predicted_labels_with_probabilities2 = {label: prob for label, prob in zip(encoder1.classes_, predicted_probabilities2[0])}
    predicted_labels_with_probabilities3 = {label: prob for label, prob in zip(encoder2.classes_, predicted_probabilities3[0])}
    predicted_labels_with_probabilities4 = {label: prob for label, prob in zip(encoder2.classes_, predicted_probabilities4[0])}
    predicted_labels_with_probabilities5 = {label: prob for label, prob in zip(encoder3.classes_, predicted_probabilities5[0])}
    predicted_labels_with_probabilities6 = {label: prob for label, prob in zip(encoder3.classes_, predicted_probabilities6[0])}

    return(predicted_labels_with_probabilities1,predicted_labels_with_probabilities2,predicted_labels_with_probabilities3,predicted_labels_with_probabilities4,predicted_labels_with_probabilities5,predicted_labels_with_probabilities6)



In [ ]:
pred_model_1=[]
pred_model_2=[]
pred_model_3=[]
pred_model_4=[]
pred_model_5=[]
pred_model_6=[]
for i in byte_sequences:
    arr=predict_symmetric(np.array([i]))
    pred_model_1.append(arr[0])
    pred_model_2.append(arr[1])
    pred_model_3.append(arr[2])
    pred_model_4.append(arr[3])
    pred_model_5.append(arr[4])
    pred_model_6.append(arr[5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 574ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 427ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
1/1 ━━━━━━━

In [ ]:
def print_val_symmetric(pred_model_1_0, pred_model_2_0):
    def ensemble_prediction(pred_model_1_0, pred_model_2_0):

        combined_predictions = {}

        combined_predictions.update(pred_model_1_0)
        combined_predictions.update(pred_model_2_0)
        final_prediction = max(combined_predictions, key=combined_predictions.get)
        return final_prediction, combined_predictions
    final_algorithm, all_predictions = ensemble_prediction(pred_model_1_0, pred_model_2_0)
    print(f"All Predictions: {all_predictions}")
    print(f"Predicted Algorithm: {final_algorithm}, Confidence: {all_predictions[final_algorithm]}")


In [ ]:
def print_val_asymmetric(pred_model_1_0, pred_model_2_0):
    def ensemble_prediction(pred_model_1_0, pred_model_2_0):
        combined_predictions = {}

        combined_predictions.update(pred_model_1_0)
        combined_predictions.update(pred_model_2_0)
        final_prediction = max(combined_predictions, key=combined_predictions.get)

        return final_prediction, combined_predictions

    final_algorithm, all_predictions = ensemble_prediction(pred_model_1_0, pred_model_2_0)
    print(f"All Predictions: {all_predictions}")
    print(f"Predicted Algorithm: {final_algorithm}, Confidence: {all_predictions[final_algorithm]}")


In [ ]:
def print_val_stream(pred_model_1_0, pred_model_2_0):
    def ensemble_prediction(pred_model_1_0, pred_model_2_0):

        combined_predictions = {}


        combined_predictions.update(pred_model_1_0)
        combined_predictions.update(pred_model_2_0)
        final_prediction = max(combined_predictions, key=combined_predictions.get)


        return final_prediction, combined_predictions


    final_algorithm, all_predictions = ensemble_prediction(pred_model_1_0, pred_model_2_0)
    print(f"All Predictions: {all_predictions}")
    print(f"Predicted Algorithm: {final_algorithm}, Confidence: {all_predictions[final_algorithm]}")


In [ ]:
for i in range(9):
    print_val_symmetric(pred_model_1[i],pred_model_2[i])
    print_val_asymmetric(pred_model_3[i],pred_model_4[i])
    print_val_stream(pred_model_5[i],pred_model_6[i])
    print()

All Predictions: {'AES-256': 0.0, 'Blowfish': 1.0, 'DES': 1.5010133e-13}
Predicted Algorithm: Blowfish, Confidence: 1.0
All Predictions: {'DSA': 4.6163424e-07, 'ECC': 6.2594705e-07, 'RSA-2048': 0.49827847, 'RSA-4096': 0.5017205}
Predicted Algorithm: RSA-4096, Confidence: 0.5017204880714417
All Predictions: {'ChaCha20': 8.902375e-10, 'RC4': 1.6851445e-21, 'Salsa20': 1.0}
Predicted Algorithm: Salsa20, Confidence: 1.0

All Predictions: {'AES-256': 0.0, 'Blowfish': 1.0, 'DES': 6.178347e-11}
Predicted Algorithm: Blowfish, Confidence: 1.0
All Predictions: {'DSA': 4.6163424e-07, 'ECC': 6.2594705e-07, 'RSA-2048': 0.49827847, 'RSA-4096': 0.5017205}
Predicted Algorithm: RSA-4096, Confidence: 0.5017204880714417
All Predictions: {'ChaCha20': 2.5395332e-06, 'RC4': 8.485567e-25, 'Salsa20': 0.9999975}
Predicted Algorithm: Salsa20, Confidence: 0.9999974966049194

All Predictions: {'AES-256': 0.0, 'Blowfish': 1.0, 'DES': 1.396321e-12}
Predicted Algorithm: Blowfish, Confidence: 1.0
All Predictions: {'DS